// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdzfizthbykgfqfgftpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkemZpenRoYnlrZ2ZxZmdmdHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjEyNjEsImV4cCI6MjA2OTI5NzI2MX0.GO40LY4b-_s5DQq-zjTbePpAsED9KUPi5nMmDh3eJQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});